Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.9/3.9.18_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig,axs = plt.subplots(2, 3,figsize=(15,8))
for i,name_train,name_test in zip ([0,1,2],fichiers_train,fichiers_test):
    train_data,train_labels = extract_data(name_train)
    test_data, test_labels = extract_data(name_test)

    model = Perceptron(train_data.shape[1])
    optimizer = optim.Adam(model.parameters())
    pltloss,acc = train_session(torch.FloatTensor(train_data),torch.FloatTensor(train_labels),model,loss,optimizer)
    
    titre= "PrÃ©cision ={0:5.3f} ".format(acc)
    plotResults(axs[0][i],axs[1][i],test_data, test_labels, model, titre, pltloss, name_test)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[7], line 6[0m
[1;32m      3[0m train_data,train_labels [38;5;241m=[39m extract_data(name_train)
[1;32m      4[0m test_data, test_labels [38;5;241m=[39m extract_data(name_test)
[0;32m----> 6[0m model [38;5;241m=[39m [43mPerceptron[49m[43m([49m[43mtrain_data[49m[38;5;241;43m.[39;49m[43mshape[49m[43m[[49m[38;5;241;43m1[39;49m[43m][49m[43m)[49m
[1;32m      7[0m optimizer [38;5;241m=[39m optim[38;5;241m.[39mAdam(model[38;5;241m.[39mparameters())
[1;32m      8[0m pltloss,acc [38;5;241m=[39m train_session(torch[38;5;241m.[39mFloatTensor(train_data),torch[38;5;241m.[39mFloatTensor(train_labels),model,loss,optimizer)

Cell [0;32mIn[5], line 12[0m, in [0;36mPerceptron.__init__[0;34m(self, p)[0m
[1;32m     10[0m [38;5;66;03m# Couche d'entrÃ©e[39;00m
[1;32m     11[0m [38;5;28mself[39m[38;5;241m.[39mfc [38;5;241m=[39m nn[38;5;241m.[39mLinear(num_features,num_labels)
[0;32m---> 12[0m [38;5;28mself[39m[38;5;241m.[39moutput [38;5;241m=[39m [43mnn[49m[38;5;241;43m.[39;49m[43mLinear[49m[43m([49m[38;5;241;43m1[39;49m[43m)[49m

[0;31mTypeError[0m: __init__() missing 1 required positional argument: 'out_features'
TypeError: __init__() missing 1 required positional argument: 'out_features'

